name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cs-poc-hpzdycpiqjyvinhrczvlwcn

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev 

      - name: Build the Docker image
        run: |
          docker build -t europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-nicolasa/quelpoke:latest .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-nicolasa/quelpoke:latest
